version: "2"

networks:
  default:
    external:
      name: docker

  mysql:
    image: mysql:5.7
    command: ["--max_connections=1000"]
    hostname: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db_service
    ports:
      - "3306:3306"
    networks:
      - default
